### ISSUE TITLE
Add command line parsing for rssync-server

### ISSUE THREAD

**Issue by tomlegodais** [tomlegodais/rssync#2]
See [clap-rs/clap](https://github.com/clap-rs/clap) for crate usage for command line parsing (prefer derive method)

You're going to have to modify `Cargo.toml` to add the `derive` feature from the clap crate:

`clap = { version = "3.0.14", features = ["derive"] }
`

**Comment by CGBassPlayer** [comment]
_Planned Argument List_

- [ ] help
- [ ] version
- [ ] add
  * List of files
- [ ] remove
  * List of files
- [ ] sync
